ALTER TABLE "Event" ADD COLUMN "organizer" TEXT NOT NULL DEFAULT 'TESCON';
ALTER TABLE "Event" ADD COLUMN "venueNote" TEXT;
ALTER TABLE "Event" ADD COLUMN "feeLabel" TEXT NOT NULL DEFAULT 'Free';
ALTER TABLE "Event" ADD COLUMN "chatUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN "attendeeImageUrls" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
